### ISSUE TITLE
Unable to load ISI's Powerloom (2010)

### ISSUE THREAD

**Issue by easye** [armedbear/abcl#186]
c.f. <https://abcl.org/trac/ticket/467>

**Comment by easye** [comment]
{{{
STELLA 3.5.35 loaded.
Type `(in-package "STELLA")' to execute STELLA commands.Making required system logic
java.lang.VerifyError: (class: org/armedbear/lisp/pl_kernel_kb_2, method: <clinit> signature: ()V) Bad type in putfield/putstatic
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
at java.lang.Class.getConstructor0(Class.java:3075)
at java.lang.Class.newInstance(Class.java:412)
at org.armedbear.lisp.FaslClassLoader.loadFunction(FaslClassLoader.java:130)
[…]
at java.lang.Thread.run(Thread.java:745)
Error loading /home/srv/powerloom-4.0.10/native/lisp/bin/lisp/logic/pl-kernel-kb.sabcl at line 44 (offset 3242)
#<THREAD "interpreter" {5B983350}>: Debugger invoked on condition of type ERROR
  Compiled function can't be loaded: org.armedbear.lisp.pl_kernel_kb_2 from org.armedbear.lisp.Pathname@54789d54
Restarts:
  0: TOP-LEVEL Return to top level.
[1] STELLA(2): 

}}}
