### ISSUE TITLE
merge-pathnames blocks error signal? <http://abcl.org/trac/ticket/433>

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#24]
`(make-pathname :directory '(:absolute ("a" "b")))`
property signals an error `Unsupported directory component (a b).`
However the following
`(merge-pathnames (make-pathname :directory '(:absolute ("a" "b"))) "")`
Does not, instead spitting out a java stack trace

```ABCL Debug.assertTrue() assertion failed!
java.lang.Error: ABCL Debug.assertTrue() assertion failed!
at org.armedbear.lisp.Debug.assertTrue(Debug.java:48)
at org.armedbear.lisp.Pathname.<init>(Pathname.java:154)
at org.armedbear.lisp.Pathname.mergePathnames(Pathname.java:1979)
at org.armedbear.lisp.Pathname$pf_merge_pathnames.execute(Pathname.java:1957)
at org.armedbear.lisp.LispThread?.execute(LispThread?.java:832)
at org.armedbear.lisp.Lisp.evalCall(Lisp.java:582)
at org.armedbear.lisp.Lisp.eval(Lisp.java:540)
at org.armedbear.lisp.Primitives$pfeval.execute(Primitives.java:345)
...
```

**Comment by Ferada** [comment]
Actually not blocking the signal, just that trying to print the pathname triggers the error (that is, not when the pathname is constructed with already invalid data). Potential fix here https://github.com/Ferada/abcl/commit/10be2b43f7e8d44cf626bcc92f186f7d541e0bdc.

**Comment by easye** [comment]
Patch has been applied as https://github.com/armedbear/abcl/commit/73341974907ce3f8e4e9626af87f5ef5e470e255
@alanruttenberg Please test and close?

**Comment by easye** [comment]
http://abcl.org/trac/ticket/433
