### ISSUE TITLE
running cl-autowrap::cl-include of an ffmpeg file breaks compile

### ISSUE THREAD

**Issue by alanruttenberg** [armedbear/abcl#431]
I probably can narrow this, but wanted to put it in because I can't do that now. To reproduce
- clone git@github.com:FFmpeg/FFmpeg.git
- Install c2ffi - the instructions [in this comment](https://github.com/rpav/c2ffi/issues/59#issuecomment-907632534) work on MacOS
- (ql:quickload "cl-autowrap")
- (autowrap::c-include <path to FFmpeg/libavutil/color_utils.c>) - use the absolute pathname
- (defun foo ())
- (compile 'foo) 

ABCL errors out with the below (or similar) and quits. Can't imagine how that's possible...

```java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 524284
	at org.armedbear.lisp.LispThread.popStackFrame(LispThread.java:827)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:900)
	at org.armedbear.lisp.Lisp$1.execute(Lisp.java:286)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:803)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:897)
	at org.armedbear.lisp.top_level_47.execute(top-level.lisp:407)
	at org.armedbear.lisp.CompiledClosure.execute(CompiledClosure.java:89)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:793)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:881)
	at org.armedbear.lisp.top_level_48.execute(top-level.lisp:415)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:881)
	at org.armedbear.lisp.Interpreter.run(Interpreter.java:361)
	at org.armedbear.lisp.Main$1.run(Main.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 524284
	at org.armedbear.lisp.LispThread.popStackFrame(LispThread.java:827)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:884)
	at org.armedbear.lisp.Interpreter.run(Interpreter.java:361)
	at org.armedbear.lisp.Main$1.run(Main.java:48)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is running with java 11, invoking ABCL with 
java --add-opens java.base/java.util=ALL-UNNAMED -jar abcl-aio.jar

My .abclrc loads the usual asdf, abcl-contrib, jss

**Comment by alanruttenberg** [comment]
> Install c2ffi - the instructions in this comment work on MacOS

Missed one thing: need to checkout branch llvm-11.0.0 of c2ffi

**Comment by Uthar** [comment]
I tested on `x86_64-linux` :

- [OpenJDK 17](https://github.com/openjdk/jdk17u/archive/jdk-17.0.1+12.tar.gz)
- [ABCL 1.8.0](https://common-lisp.net/project/armedbear/releases/1.8.0/abcl-src-1.8.0.tar.gz)
- [cl-autowrap](http://beta.quicklisp.org/archive/cl-autowrap/2021-12-09/cl-autowrap-20211209-git.tgz)
- [c2ffi](https://github.com/rpav/c2ffi/archive/f50243926a0afb589de1078a073ac08910599582.tar.gz)
- [FFmpeg](https://github.com/FFmpeg/FFmpeg/archive/0d666200d30be1643aa46fa67073f257c11937ac.tar.gz)

running these commands:
```
java --add-opens=java.base/java.util.jar=ALL-UNNAMED -cp "abcl.jar:abcl-contrib.jar:jna-5.9.0.jar" org.armedbear.lisp.Main
(require 'asdf)
(require 'cl-autowrap)
(autowrap::c-include "/.../ffmpeg/libavutil/color_utils.c")
(defun foo ())
(compile 'foo)
```

No error there
