### ISSUE TITLE
JDK19 threading support

### ISSUE THREAD

**Issue by bohonghuang** [armedbear/abcl#514]
On OpenJDK19, the following warning is emitted by ABCL on every startup:

```
Failed to introspect virtual threading methods: java.lang.NoSuchMethodException: java.lang.Thread.builder()
```

And NPE is thrown when creating a thread:

```
java.lang.NullPointerException: Cannot enter synchronized block because "org.armedbear.lisp.LispThread.threadBuilder" is null
	at org.armedbear.lisp.LispThread.<init>(LispThread.java:186)
	at org.armedbear.lisp.LispThread$3.execute(LispThread.java:1271)
	at org.armedbear.lisp.Primitive.execute(Primitive.java:135)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:828)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:945)
	at org.armedbear.lisp.impl_abcl_tmp209RB6YX_1.execute(impl-abcl.lisp:18)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:816)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:924)
	at org.armedbear.lisp.default_implementations_tmp6MEJ867E_7.execute(default-implementations.lisp:29)
	at org.armedbear.lisp.CompiledClosure.execute(CompiledClosure.java:98)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:904)
	at org.armedbear.lisp.Lisp.evalCall(Lisp.java:623)
	at org.armedbear.lisp.Lisp.eval(Lisp.java:588)
	at org.armedbear.lisp.Primitives$pf__eval.execute(Primitives.java:346)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:904)
	at org.armedbear.lisp.Lisp.evalCall(Lisp.java:623)
	at org.armedbear.lisp.Lisp.eval(Lisp.java:588)
	at org.armedbear.lisp.Lisp.progn(Lisp.java:749)
	at org.armedbear.lisp.Primitives$sf_block.execute(Primitives.java:3752)
	at org.armedbear.lisp.Lisp.eval(Lisp.java:569)
	at org.armedbear.lisp.Lisp.progn(Lisp.java:749)
	at org.armedbear.lisp.Closure.execute(Closure.java:220)
	at org.armedbear.lisp.Closure.execute(Closure.java:148)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:904)
	at org.armedbear.lisp.Lisp$1.execute(Lisp.java:286)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:805)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:904)
	at org.armedbear.lisp.top_level_47.execute(top-level.lisp:407)
	at org.armedbear.lisp.CompiledClosure.execute(CompiledClosure.java:89)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:795)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:886)
	at org.armedbear.lisp.top_level_48.execute(top-level.lisp:415)
	at org.armedbear.lisp.LispThread.execute(LispThread.java:886)
	at org.armedbear.lisp.Interpreter.run(Interpreter.java:361)
	at org.armedbear.lisp.Main$1.run(Main.java:48)
	at java.base/java.lang.Thread.run(Thread.java:1589)
#<THREAD "interpreter" {3AA97666}>: Debugger invoked on condition of type ERROR
```

**Comment by easye** [comment]
Note that ABCL is not currently tested beyond openjdk17:  glad to know that it still works in JDK19!

**Comment by bohonghuang** [comment]
> Note that ABCL is not currently tested beyond openjdk17: glad to know that it still works in JDK19!

I've played with ABCL on JDK18 for months, and it works fine. The broken thread seems due to the introduction of the virtual thread in JDK19.

**Comment by easye** [comment]
Verified that we don't run under openjdk19.  

From reading <https://openjdk.org/jeps/425> especially the part 

```
Enable existing code that uses the java.lang.Thread API to adopt virtual threads with minimal change.
```

seems to indicate that we should possibly file an issue with the openjdk19 group as per acceptance.  

I'll take a crack at looking at the API I used to introspect the threads made available in Project Loom <https://blogs.oracle.com/javamagazine/post/going-inside-javas-project-loom-and-virtual-threads> for abcl-1.7.0.  I tried to use the method that looked most general at the time but perhaps I misunderstood, or ORCL/openjdk changed their minds…

**Comment by easye** [comment]
I can't quite get the virtual threads to work, yet.  We need to be able to dynamically introspect the classes present in the runtime jdk in order to progressively see what threading features are present.  JEP425 wants to do this by using static interfaces ("java.lang.Thread$Builder$OfVirtual", usw.) which I currently can't get to work on openjdk8 or openjdk11.  

The commits in <https://github.com/armedbear/abcl/pull/528>:

1.  Enable testing in the CI under openjdk19

2.  Start to patch LispThread to the point that if when it fails to dynamically introspect the existence of virtual threads (for reasons that I am in the middle of debugging) it falls back to native threads.

**Comment by easye** [comment]
After more self-education on the state of things, I have distilled my problems in implementing starting a a virtual thread on openjdk19 to the following pure-Java example.

@bohonghuang Perhaps you could try to run the following to explain where I am going wrong?  

The following example, run with openjdk-19.0.1 with command line arguments `--enable-preview --add-opens java.base/java.lang=ALL-UNNAMED`:

```
package org.not;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Reflect {

    static Object virtualThreadFactory;
    static Method newThread;
    
    public static void main(String[] args) {
        try {
            Class c = Class.forName("java.lang.Thread");
            Method ofVirtualMethod = c.getMethod("ofVirtual");
            Object threadBuilderOfVirtual = ofVirtualMethod.invoke(null);
            Class factoryMethodClass = threadBuilderOfVirtual.getClass();
            Method factoryMethod = factoryMethodClass.getMethod("factory");
            Class virtualThreadFactoryClass = Class.forName("java.lang.ThreadBuilders$VirtualThreadFactory");
            virtualThreadFactory = factoryMethod.invoke(virtualThreadFactoryClass, (Object[]) null);
            newThread = virtualThreadFactory.getClass().getMethod("newThread");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Reflect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(Reflect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(Reflect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Reflect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvocationTargetException ex) {
            Logger.getLogger(Reflect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
```


gives the following error 


```
Dec 01, 2022 8:29:47 AM org.not.Reflect main
SEVERE: null
java.lang.IllegalAccessException: class org.not.Reflect cannot access a member of class java.lang.ThreadBuilders$VirtualThreadBuilder (in module java.base) with modifiers "public"
```

The equivalent code in ABCL with JSS seems to work just fine:  

```
(let ((runnable 
        (java:jinterface-implementation "java.lang.Runnable" "run" (lambda ())))
      (thread-factory
        (java:jcall "factory"
                    (java:jcall "ofVirtual" (java:jnew "java.lang.Thread")))))
  (java:jcall "newThread" thread-factory runnable))
```

**Comment by easye** [comment]
> It may reveal that all the expressions evaluated in REPL are actually executed under the Java internal package.

Apparently, I need to understand the Java Module system better.  I had though that the ABCL process code is executing in an "unnamed" module, and hence would be covered by the JVM `--add-opens` switch.  

I am going through the relevant JEPs now, but it will take some time for my brain to absorb. 

If anyone has recommendations for decent resources on learning about Java Modules, especially as to how to support our codebase running on all LTS JDKs (openjdk{8,11,17}) plus the current development JDK (openjdk19 now, openjdk20 when binaries start getting released), I would appreciate it.  

I think we need to start declaring a module for the `org.armedbear.lisp.*` code that we can open the reflection APIs to, but I am still coming to an understanding here.

**Comment by easye** [comment]
I've [filed an openjdk issue][1] about this problem, while I continue to research things on my own.  


[1]: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8298011

**Comment by easye** [comment]
After some work, the code in the openjdk issue <https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8298011> led me to seemingly fix things with <https://github.com/armedbear/abcl/pull/530>.

**Comment by easye** [comment]
Fixed via <https://github.com/armedbear/abcl/pull/530>
